#[cfg(test)]
mod tests 
{
    use crate::problem::*;

    const TEST_STR: &str = r"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............";

    #[test]
    fn part_1_test() 
    {
        let result = problem::count_antinodes_in_grid(&String::from(TEST_STR));
        assert_eq!(result, 14);
    }

    #[test]
    fn part_2_test() 
    {
         let result = problem::count_harmonics_in_grid(&String::from(TEST_STR));
         assert_eq!(result, 34);
    }
}